ROOTDIR = $(shell pwd)
SDIR = ${ROOTDIR}/src
IDIR = ${ROOTDIR}/include
ODIR = ${ROOTDIR}/obj
BDIR = ${ROOTDIR}/bin

vpath %.h ${IDIR}
vpath %.cpp ${SDIR}

CC 				= g++
CPPFLAGS 		= -I${IDIR}
LDFLAGS 		= -larmadillo

OBJ0 			= 
OBJS 			= $(patsubst %, ${ODIR}/%.o, ${OBJ0})

main 			: ${OBJS} ${STATIC_LIBS} ${SHARED_LIBS} | ${BDIR}
	${CC} ${OBJS} -o ${BDIR}/$@ ${CPPFLAGS} ${LDFLAGS}

test 			: test_fermi test_newtonroot

test_% 			: ${ODIR}/test_%.o ${ODIR}/%.o | ${BDIR}
	${CC} $^ -o ${BDIR}/$@ ${CPPFLAGS} ${LDFLAGS}

${ODIR}/main.o 	: main.cpp | ${ODIR}
	${CC} -c $< -o $@ ${CPPFLAGS}

${ODIR}/test_%.o : test_%.cpp | ${ODIR}
	${CC} -c $< -o $@ ${CPPFLAGS}

${ODIR}/%.o		: %.cpp %.h | ${ODIR}
	${CC} -c $< -o $@ ${CPPFLAGS}

${BDIR} ${ODIR} ${LDIR} :
	mkdir -p $@

.PRECIOUS: ${ODIR}/%.o ${ODIR}/test_%.o
.PHONY: clean

clean:
	rm -rf ${ODIR} ${BDIR} ${LDIR}

